name: Run tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        # Note: Caching (of the packages that `uv` builds while resolving dependencies) is "enabled by default on GitHub-hosted runners."
        #       Reference: https://github.com/astral-sh/setup-uv/blob/main/README.md#enable-caching
        #       Here, we make it so the cache gets invalidated whenever the `uv.lock` file changes.
        #       Reference: https://github.com/astral-sh/setup-uv/blob/main/README.md#cache-dependency-glob
        cache-dependency-glob: "uv.lock"
    - name: Set up Python virtual environment
      run: uv sync
    - name: Check format
      run: uv run ruff format --diff
    - name: Lint code
      run: uv run ruff check
    - name: Run tests
      run: uv run pytest --cov
